# :schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "specter119"
email = "specter119@gmail.com"

[aliases]
push = ["util", "exec", "--", "jj-pre-push", "push"]

# {{#if git.repo_identities}}{{#each git.repo_identities}}

[[--scope]]
--when.repositories = ["{{repo_dir}}"]

[--scope.user]
name = "{{name}}"
email = "{{email}}"

# {{/each}}{{/if}}
