# 小宇宙播客订阅列表

[[track]]
path = "https://feed.xyzfm.space/xlgejk3wbj8q"
title = "霓达播客"
feed = true

[[track]]
path = "https://feed.xyzfm.space/49cgd8grgrnf"
title = "人民公园说AI"
feed = true

[[track]]
path = "https://feed.xyzfm.space/wmnkvmrpwuww"
title = "罗永浩的十字路口"
feed = true

[[track]]
path = "https://feed.xyzfm.space/dk4yh3pkpjp3"
title = "张小珺Jùn｜商业访谈录"
feed = true

[[track]]
path = "https://feed.xyzfm.space/evgg6xle9rdc"
title = "42章经"
feed = true

[[track]]
path = "https://feed.xyzfm.space/68fyjknth9hj"
title = "十字路口Crossing"
feed = true

[[track]]
path = "https://feed.xyzfm.space/834hyx3v9k74"
title = "屠龙之术"
feed = true

[[track]]
path = "https://feed.xyzfm.space/nfm8cu8deycn"
title = "代码之外 Beyond Code"
feed = true

[[track]]
path = "https://feed.xyzfm.space/6ngqmrnrkahw"
title = "和盘托出"
feed = true

[[track]]
path = "https://feed.xyzfm.space/ypn9dydpbxpc"
title = "无人知晓"
feed = true

[[track]]
path = "https://feed.xyzfm.space/3l346yhchx84"
title = "美西螈与东方巨龙"
feed = true

[[track]]
path = "https://feed.xyzfm.space/cv4bkgpuglwp"
title = "忽左忽右"
feed = true

[[track]]
path = "https://www.ximalaya.com/album/64689453.xml"
title = "蜜獾吃书"
feed = true

[[track]]
path = "https://feed.xyzfm.space/vylham8uw3ay"
title = "半拿铁·周刊"
feed = true

[[track]]
path = "https://feed.xyzfm.space/tcettvc3x689"
title = "半拿铁 | 商业沉浮录"
feed = true

[[track]]
path = "https://feed.xyzfm.space/l3c8em3l8hfn"
title = "李诞"
feed = true

[[track]]
path = "https://feed.xyzfm.space/epcnnjpdrk7y"
title = "重重电波"
feed = true

[[track]]
path = "https://feed.xyzfm.space/kf7lym7fc4e9"
title = "此话当真"
feed = true
